name: ARM64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,ubuntu:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Free Disk Space and Relocate Docker
      run: |
        # 1. 停止 Docker 服务
        sudo systemctl stop docker
        
        # 2. 创建存放 Docker 数据的新目录（在那个 101G 的分区上）
        sudo mkdir -p /home/runner/work/docker-data
        
        # 3. 迁移现有的 Docker 数据 (如果已经有部分数据的话)
        # 注意：这一步如果数据量大可能会耗时，但为了确保一致性建议执行
        # 或者直接清空旧目录：sudo rm -rf /var/lib/docker/*
        sudo rsync -aP /var/lib/docker/ /home/runner/work/docker-data/
        
        # 4. 修改 Docker 配置文件，指向新位置
        # 使用 tee 写入 daemon.json
        echo '{
          "data-root": "/home/runner/work/docker-data"
        }' | sudo tee /etc/docker/daemon.json
        
        # 5. 重新启动 Docker
        sudo systemctl start docker
        
        # 6. 验证 Docker 根目录已更改
        docker info | grep "Docker Root Dir"
        
    - name: Pull Docker Images and Package
      env:
        DOCKER_TMPDIR: /home/runner/work/tmp
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/arm64"
          docker save "${image}" -o "${image//\//_}-arm64.tar"
        done

    - name: Compress the TAR files
      run: tar -czf arm64-images.tar.gz *-arm64.tar

    - name: Upload to OSS
      uses: modstart/github-oss-action@master
      with:
        key-id: ${{ secrets.OSS_KEY_ID }}
        key-secret: ${{ secrets.OSS_KEY_SECRET }}
        region: ${{ secrets.OSS_REGION }}
        bucket: ${{ secrets.OSS_BUCKET }}
        assets: |
          arm64-images.tar.gz:/arm64-images.tar.gz

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: docker-images-tar
    #     path: arm64-images.tar.gz
    #     retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-arm64.tar
